[DEFAULT]
; Set this to Yes if you want to reset your config (Yes or No)
ResetConfig=No

; Low, Normal or High (defaults to Normal)
TimerLength=Normal
TimerSpeed=Normal

; Low, Normal, High or Off (defaults to Off)
QuickTime=Low
AshChance=Normal

; Yes or No
OnlyQuickTime=No
AlwaysAsh=No
FastTimer=No
AshWarning=No
HideTimer=No
GamingSafety=No
TimerTicks=Yes
FreakyTick=No
EmergencyExit=No
DisownProtection=No
FakeWarn=No
HideMessage=No
Gas=Yes
IRL=Yes

; Any color except green (Red, Orange, Yellow, Blue, Purple or White, defaults to Red)
TimerColor=Red

; Experimental?? (Yes or No)
Balls=Yes
Yes=Yes
No=No
Torture=No